cc_binary(
    name = "proto2json",
    srcs = ["main.cc"],
    deps = [
        "//external:gflags",
        "//external:glog",
        "@com_google_protobuf_cc//:cc_wkt_protos",
        "@com_google_protobuf_cc//:protobuf",
    ],
)
